language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: true
before_install:
  - sudo apt-get install libc6
  - sudo apt-get install gfortran
install:
  - pip install -U .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
