language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
#  - "3.7"
dist: xenial
sudo: true
before_install:
  - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - sudo apt-get update
  - sudo apt-get install libc6
  - sudo apt-get install gfortran
install:
  - conda create --yes -n mogu-test python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - source activate mogu-test
  - pip install -U Cython
  - pip install -U pandas
  - pip install -U .
# command to run tests
script:
  - python setup.py test # or py.test for Python versions 3.5 and below
